<a href="https://colab.research.google.com/github/ahydeishere/CSE-450-machine-learning/blob/main/Assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction
This assignment will test how well you're able to perform various data science-related tasks.

Each Problem Group below will center around a particular dataset that you have worked with before.

To ensure you receive full credit for a question, make sure you demonstrate the appropriate pandas, altair, or other commands as requested in the provided code blocks.

You may find that some questions require multiple steps to fully answer. Others require some mental arithmetic in addition to pandas commands. Use your best judgment.

## Submission
Each problem group asks a series of questions. This assignment consists of two submissions:

1. After completing the questions below, open the Module 01 Assessment Quiz in Canvas and enter your answers to these questions there.

2. After completing and submitting the quiz, save this Colab notebook as a GitHub Gist (You'll need to create a GitHub account for this), by selecting `Save a copy as a GitHub Gist` from the `File` menu above.

    In Canvas, open the Module 01 Assessment GitHub Gist assignment and paste the GitHub Gist URL for this notebook. Then submit that assignment.

## Problem Group 1

For the questions in this group, you'll work with the Netflix Movies Dataset found at this url: [https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/netflix_titles.csv](https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/netflix_titles.csv)

### Question 1
Load the dataset into a Pandas data frame and determine what data type is used to store the `release_year` feature.

In [ ]:
import pandas as pd
import numpy as np
import polars as pl
from lets_plot import *

LetsPlot.setup_html(isolated_frame = True)

netflix_df = pl.read_csv("https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/netflix_titles.csv")

netflix_df.describe()

shape: (9, 13)
┌────────────┬────────────┬─────────┬────────────┬───┬────────┬──────────┬────────────┬────────────┐
│ statistic  ┆ show_id    ┆ type    ┆ title      ┆ … ┆ rating ┆ duration ┆ listed_in  ┆ descriptio │
│ ---        ┆ ---        ┆ ---     ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---        ┆ n          │
│ str        ┆ f64        ┆ str     ┆ str        ┆   ┆ str    ┆ str      ┆ str        ┆ ---        │
│            ┆            ┆         ┆            ┆   ┆        ┆          ┆            ┆ str        │
╞════════════╪════════════╪═════════╪════════════╪═══╪════════╪══════════╪════════════╪════════════╡
│ count      ┆ 6234.0     ┆ 6234    ┆ 6234       ┆ … ┆ 6224   ┆ 6234     ┆ 6234       ┆ 6234       │
│ null_count ┆ 0.0        ┆ 0       ┆ 0          ┆ … ┆ 10     ┆ 0        ┆ 0          ┆ 0          │
│ mean       ┆ 7.6704e7   ┆ null    ┆ null       ┆ … ┆ null   ┆ null     ┆ null       ┆ null       │
│ std        ┆ 1.0943e7   ┆ null    ┆ null       ┆ … ┆ null   ┆ null     ┆ null       ┆ null       │
│ min        ┆ 247747.0   ┆ Movie   ┆ #Roxy      ┆ … ┆ G      ┆ 1 Season ┆ Action &   ┆ "Brooklyn  │
│            ┆            ┆         ┆            ┆   ┆        ┆          ┆ Adventure  ┆ Nine-Nine" │
│            ┆            ┆         ┆            ┆   ┆        ┆          ┆            ┆ star Chel… │
│ 25%        ┆ 8.0035689e ┆ null    ┆ null       ┆ … ┆ null   ┆ null     ┆ null       ┆ null       │
│            ┆ 7          ┆         ┆            ┆   ┆        ┆          ┆            ┆            │
│ 50%        ┆ 8.0163368e ┆ null    ┆ null       ┆ … ┆ null   ┆ null     ┆ null       ┆ null       │
│            ┆ 7          ┆         ┆            ┆   ┆        ┆          ┆            ┆            │
│ 75%        ┆ 8.02449e7  ┆ null    ┆ null       ┆ … ┆ null   ┆ null     ┆ null       ┆ null       │
│ max        ┆ 8.1235729e ┆ TV Show ┆ 최강전사   ┆ … ┆ UR     ┆ 99 min   ┆ Thrillers  ┆ Zixin is   │
│            ┆ 7          ┆         ┆ 미니특공대 ┆   ┆        ┆          ┆            ┆ about to   │
│            ┆            ┆         ┆ : 영웅의   ┆   ┆        ┆          ┆            ┆ marry      │
│            ┆            ┆         ┆ 탄생       ┆   ┆        ┆          ┆            ┆ Qihong…    │
└────────────┴────────────┴─────────┴────────────┴───┴────────┴──────────┴────────────┴────────────┘

### Question 2
Filter your dataset so it contains only `TV Shows`. How many of those TV Shows were rated `TV-Y7`?

In [ ]:
netflix_df.filter(pl.col("type") == "TV Show").filter(pl.col("rating") == "TV-Y7").count(   )

shape: (1, 12)
┌─────────┬──────┬───────┬──────────┬───┬────────┬──────────┬───────────┬─────────────┐
│ show_id ┆ type ┆ title ┆ director ┆ … ┆ rating ┆ duration ┆ listed_in ┆ description │
│ ---     ┆ ---  ┆ ---   ┆ ---      ┆   ┆ ---    ┆ ---      ┆ ---       ┆ ---         │
│ u32     ┆ u32  ┆ u32   ┆ u32      ┆   ┆ u32    ┆ u32      ┆ u32       ┆ u32         │
╞═════════╪══════╪═══════╪══════════╪═══╪════════╪══════════╪═══════════╪═════════════╡
│ 100     ┆ 100  ┆ 100   ┆ 7        ┆ … ┆ 100    ┆ 100      ┆ 100       ┆ 100         │
└─────────┴──────┴───────┴──────────┴───┴────────┴──────────┴───────────┴─────────────┘

### Question 3
Further filter your dataset so it only contains TV Shows released between the years 2000 and 2009 inclusive. How many of *those* shows were rated `TV-Y7`?

In [ ]:
netflix_df.filter(pl.col("type") == "TV Show").filter(pl.col("rating") == "TV-Y7").filter(pl.col("release_year") >= 2000).filter(pl.col("release_year") <= 2009).count()

shape: (1, 12)
┌─────────┬──────┬───────┬──────────┬───┬────────┬──────────┬───────────┬─────────────┐
│ show_id ┆ type ┆ title ┆ director ┆ … ┆ rating ┆ duration ┆ listed_in ┆ description │
│ ---     ┆ ---  ┆ ---   ┆ ---      ┆   ┆ ---    ┆ ---      ┆ ---       ┆ ---         │
│ u32     ┆ u32  ┆ u32   ┆ u32      ┆   ┆ u32    ┆ u32      ┆ u32       ┆ u32         │
╞═════════╪══════╪═══════╪══════════╪═══╪════════╪══════════╪═══════════╪═════════════╡
│ 4       ┆ 4    ┆ 4     ┆ 0        ┆ … ┆ 4      ┆ 4        ┆ 4         ┆ 4           │
└─────────┴──────┴───────┴──────────┴───┴────────┴──────────┴───────────┴─────────────┘

## Problem Group 2

For the questions in this group, you'll work with the Cereal Dataset found at this url: [https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/cereal.csv](https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/cereal.csv)

### Question 4
After importing the dataset into a pandas data frame, determine the median amount of `protein` in cereal brands manufactured by Kelloggs. (`mfr` code "K")

In [ ]:
cereal_df = pd.read_csv("https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/cereal.csv")

cereal_df.loc[cereal_df["mfr"] == "K"]["protein"].median()

3.0

### Question 5
In order to comply with new government regulations, all cereals must now come with a "Healthiness" rating. This rating is calculated based on this formula:

    healthiness = (protein + fiber) / sugar

Create a new `healthiness` column populated with values based on the above formula.

Then, determine the median healthiness value for only General Mills cereals (`mfr` = "G"), rounded to two decimal places.

In [ ]:
cereal_df = pl.from_pandas(cereal_df)

cereal_df = (
    cereal_df
    .with_columns(
        (
            (pl.col("protein") + pl.col("fiber")) / pl.col("sugars")
        ).alias("healthiness")
    )
    .filter(pl.col("mfr") == "G")
)

cereal_df.select(pl.col("healthiness").median())

shape: (1, 1)
┌─────────────┐
│ healthiness │
│ ---         │
│ f64         │
╞═════════════╡
│ 0.475       │
└─────────────┘

## Problem Group 3

For the questions in this group, you'll work with the Titanic Dataset found at this url: [https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv](https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv)

### Question 6

After loading the dataset into a pandas DataFrame, create a new column called `NameGroup` that contains the first letter of the passenger's surname in lower case.

Note that in the dataset, passenger's names are provided in the `Name` column and are listed as:

    Surname, Given names

For example, if a passenger's `Name` is `Braund, Mr. Owen Harris`, the `NameGroup` column should contain the value `b`.

Then count how many passengers have a `NameGroup` value of `k`.

In [ ]:
titanic_df = pd.read_csv("https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv")

titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,No,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,Yes,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,Yes,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,Yes,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,No,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic_df["NameGroup"] = titanic_df["Name"].str.split(",").str[0].str[0].str.lower()

sum_k = (titanic_df["NameGroup"] == "k").sum()

print(sum_k)

28